// Generated by gencpp from file lab4_cam/CentroidSrvResponse.msg
// DO NOT EDIT!


#ifndef LAB4_CAM_MESSAGE_CENTROIDSRVRESPONSE_H
#define LAB4_CAM_MESSAGE_CENTROIDSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace lab4_cam
{
template <class ContainerAllocator>
struct CentroidSrvResponse_
{
  typedef CentroidSrvResponse_<ContainerAllocator> Type;

  CentroidSrvResponse_()
    : centroid()  {
    }
  CentroidSrvResponse_(const ContainerAllocator& _alloc)
    : centroid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;




  typedef boost::shared_ptr< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CentroidSrvResponse_

typedef ::lab4_cam::CentroidSrvResponse_<std::allocator<void> > CentroidSrvResponse;

typedef boost::shared_ptr< ::lab4_cam::CentroidSrvResponse > CentroidSrvResponsePtr;
typedef boost::shared_ptr< ::lab4_cam::CentroidSrvResponse const> CentroidSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab4_cam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eb286b1528e6357255e84ebb1efd9d1";
  }

  static const char* value(const ::lab4_cam::CentroidSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eb286b1528e6357ULL;
  static const uint64_t static_value2 = 0x255e84ebb1efd9d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab4_cam/CentroidSrvResponse";
  }

  static const char* value(const ::lab4_cam::CentroidSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point centroid\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::lab4_cam::CentroidSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.centroid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CentroidSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab4_cam::CentroidSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab4_cam::CentroidSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB4_CAM_MESSAGE_CENTROIDSRVRESPONSE_H
