// Generated by gencpp from file lab4_cam/CentroidSrv.msg
// DO NOT EDIT!


#ifndef LAB4_CAM_MESSAGE_CENTROIDSRV_H
#define LAB4_CAM_MESSAGE_CENTROIDSRV_H

#include <ros/service_traits.h>


#include <lab4_cam/CentroidSrvRequest.h>
#include <lab4_cam/CentroidSrvResponse.h>


namespace lab4_cam
{

struct CentroidSrv
{

typedef CentroidSrvRequest Request;
typedef CentroidSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CentroidSrv
} // namespace lab4_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab4_cam::CentroidSrv > {
  static const char* value()
  {
    return "9eb286b1528e6357255e84ebb1efd9d1";
  }

  static const char* value(const ::lab4_cam::CentroidSrv&) { return value(); }
};

template<>
struct DataType< ::lab4_cam::CentroidSrv > {
  static const char* value()
  {
    return "lab4_cam/CentroidSrv";
  }

  static const char* value(const ::lab4_cam::CentroidSrv&) { return value(); }
};


// service_traits::MD5Sum< ::lab4_cam::CentroidSrvRequest> should match 
// service_traits::MD5Sum< ::lab4_cam::CentroidSrv > 
template<>
struct MD5Sum< ::lab4_cam::CentroidSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab4_cam::CentroidSrv >::value();
  }
  static const char* value(const ::lab4_cam::CentroidSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab4_cam::CentroidSrvRequest> should match 
// service_traits::DataType< ::lab4_cam::CentroidSrv > 
template<>
struct DataType< ::lab4_cam::CentroidSrvRequest>
{
  static const char* value()
  {
    return DataType< ::lab4_cam::CentroidSrv >::value();
  }
  static const char* value(const ::lab4_cam::CentroidSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab4_cam::CentroidSrvResponse> should match 
// service_traits::MD5Sum< ::lab4_cam::CentroidSrv > 
template<>
struct MD5Sum< ::lab4_cam::CentroidSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab4_cam::CentroidSrv >::value();
  }
  static const char* value(const ::lab4_cam::CentroidSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab4_cam::CentroidSrvResponse> should match 
// service_traits::DataType< ::lab4_cam::CentroidSrv > 
template<>
struct DataType< ::lab4_cam::CentroidSrvResponse>
{
  static const char* value()
  {
    return DataType< ::lab4_cam::CentroidSrv >::value();
  }
  static const char* value(const ::lab4_cam::CentroidSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB4_CAM_MESSAGE_CENTROIDSRV_H
