// Generated by gencpp from file lab4_cam/CentroidSrvRequest.msg
// DO NOT EDIT!


#ifndef LAB4_CAM_MESSAGE_CENTROIDSRVREQUEST_H
#define LAB4_CAM_MESSAGE_CENTROIDSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab4_cam
{
template <class ContainerAllocator>
struct CentroidSrvRequest_
{
  typedef CentroidSrvRequest_<ContainerAllocator> Type;

  CentroidSrvRequest_()
    {
    }
  CentroidSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CentroidSrvRequest_

typedef ::lab4_cam::CentroidSrvRequest_<std::allocator<void> > CentroidSrvRequest;

typedef boost::shared_ptr< ::lab4_cam::CentroidSrvRequest > CentroidSrvRequestPtr;
typedef boost::shared_ptr< ::lab4_cam::CentroidSrvRequest const> CentroidSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab4_cam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lab4_cam::CentroidSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab4_cam/CentroidSrvRequest";
  }

  static const char* value(const ::lab4_cam::CentroidSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::lab4_cam::CentroidSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CentroidSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab4_cam::CentroidSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lab4_cam::CentroidSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LAB4_CAM_MESSAGE_CENTROIDSRVREQUEST_H
