(cl:defpackage lab4_cam-srv
  (:use )
  (:export
   "IMAGESRV"
   "<IMAGESRV-REQUEST>"
   "IMAGESRV-REQUEST"
   "<IMAGESRV-RESPONSE>"
   "IMAGESRV-RESPONSE"
   "CENTROIDSRV"
   "<CENTROIDSRV-REQUEST>"
   "CENTROIDSRV-REQUEST"
   "<CENTROIDSRV-RESPONSE>"
   "CENTROIDSRV-RESPONSE"
   "CAMINFOSRV"
   "<CAMINFOSRV-REQUEST>"
   "CAMINFOSRV-REQUEST"
   "<CAMINFOSRV-RESPONSE>"
   "CAMINFOSRV-RESPONSE"
  ))

